name: Negi Monitor Test

on:
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: self-hosted

    steps:
    - name: 1. Checkout
      uses: actions/checkout@v4

    - name: 2. Launch Windows Camera App
      run: |
        Write-Host "START CAMERA TEST"
        powershell -Command "start microsoft.windows.camera:"
        Start-Sleep -Seconds 5
        Write-Host "END CAMERA TEST"
